---
#- hosts: all
#  gather_facts: no 
#  sudo: true
#  tasks:
#  - name: Check for python json
#    raw: python -c "import json"
#    register: python_json
#    ignore_errors: True
#    sudo: false
#
#  - name: Check for python json
#    raw: python -c "import simplejson"
#    register: python_simplejson
#    ignore_errors: True
#    sudo: false
#
#  - name: Install Python simplejson
#    raw: yum -y install python-simplejson
#    when: python_json|failed and python_simplejson|failed

- hosts: all 
  gather_facts: yes
  sudo: true
  tasks:
  - include: tasks/RedHat5-conntrack.yml 
    when:
      ansible_distribution != 'Amazon' and ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6
 

  - include: tasks/RedHat6-conntrack.yml
    when:
      ansible_distribution == 'Amazon' or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6)

