---


- name: Check conntrack_max for CentOS5
  raw: cat /proc/sys/net/ipv4/netfilter/ip_conntrack_max 
  register: conntrack_OS5
  ignore_errors: True

- name: Change conntrack_max for CentOS5 if the value less then 655360
  raw: echo 655360 > /proc/sys/net/ipv4/netfilter/ip_conntrack_max
  ignore_errors: True
  register: OS5_result
  when: 
    conntrack_OS5.rc == 0 and conntrack_OS5.stdout|int < 655360

- name: Check if sysctl settings are already in sysctl.conf
  raw: grep "ip_conntrack_max" /etc/sysctl.conf| tail -1| sed 's/^\s*//' |grep -v "^#"|awk '{print $3}'
  ignore_errors: True
  register: OS5_sysctl_check

- name: Ensure sysctl settings are properly applied (CentOS5)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=no
    sysctl_set=no
  ignore_errors: True
  with_dict: 
    sysctl_centos5
  when:
    OS5_sysctl_check.stdout|int < 655360 or OS5_sysctl_check.stdout == ""

- name: Check conntrack_max again and record final value to the log file conntrack.txt
  raw: cat /proc/sys/net/ipv4/ip_conntrack_max ; grep "ip_conntrack_max" /etc/sysctl.conf|tail -1| sed 's/^\s*//' |grep -v "^#" 
  ignore_errors: True

