---
- name: Check conntrack_max for CentOS6
  raw: cat /proc/sys/net/netfilter/nf_conntrack_max
  register: conntrack_OS6
  ignore_errors: True

- name: Change conntrack_max for CentOS6 if the value less then 655360
  raw: echo 655360 > /proc/sys/net/netfilter/nf_conntrack_max 
  ignore_errors: True
  register: OS6_result
  when: 
    conntrack_OS6.rc == 0 and conntrack_OS6.stdout|int < 655360

- name: Check if sysctl settings are already in sysctl.conf file
  raw: grep "nf_conntrack_max" /etc/sysctl.conf| tail -1 |sed 's/^\s*//' |grep -v "^#"|awk '{print $3}'
  ignore_errors: True
  register: OS6_sysctl_check

- name: Ensure sysctl settings are properly applied (CentOS6)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=no
    sysctl_set=no
  ignore_errors: True
  with_dict: 
    sysctl_centos6
  when:
    OS6_sysctl_check.rc == "" or OS6_sysctl_check.stdout|int < 655360

- name: Check conntrack_max again  and record final value to the log file conntrack.txt
  raw: cat /proc/sys/net/netfilter/nf_conntrack_max ; grep "nf_conntrack_max" /etc/sysctl.conf| tail -1 |sed 's/^\s*//' |grep -v "^#" 
  ignore_errors: True



